version: '3.1'

volumes:
  jenkins-data:
    driver: local
services: 
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-master
    volumes:
      - jenkins-data:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
  jenkins-ssh-slave:
    image: "jenkins/ssh-slave"
    ports:
      - ${PORT}:22/tcp
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=${JENKINS_SLAVE_SSH_PUBKEY}