version: '3.7'

volumes:
  jenkins-data:
    driver: local
services: 
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-master
    volumes:
      - jenkins-data:/var/jenkins_home
      - ./casc_configs:/var/jenkins_home/casc_configs
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
  prometheus:
      image: prom/prometheus:latest
      volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
      command:
          - "--config.file=/etc/prometheus/prometheus.yml"
      ports:
          - "9090:9090"