---
# prometheus.yml
global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: jenkins_job

    basic_auth:
      username: demoAdmin
      password: passw0rd
    
    metrics_path: /prometheus
    
    static_configs:
      - targets: ['jenkins-master:8080']